service_name: 'Nordea Analytics API'
max_bonds: 50
max_symbol_timeseries: 50
max_keyfigures_timeseries: 1
max_years_timeseries: 10

url_suffix:
  bond_key_figures: "bonds/keyfigure"
  calculate: "bonds-calculation"
  calculate_advanced: "bonds-advanced-calculation"
  calculate_horizon: "bonds-horizoncalculation"
  bond_static_data: "bonds/static-data"
  curve: "curves"
  curve_definition: "curves/definition"
  curve_time_series: "curves/timeseries"
  fx_forecast: "fx-forecasts"
  fx_quotes: "quotes"
  index_composition: "index-composition"
  search_bonds: "search/bonds"
  search_dmb_bonds: "search/danishmortgagebonds"
  live_bond_key_figures: "bonds/live-keyfigures"
  shift_days: "shift-days"
  time_series: "timeseries"
  year_fraction: "year-fraction"
  yield_forecast: "yield-forecasts"


#Squashes json response layers
results:
  bond_key_figures: "keyfigures"
  bond_static_data: "static_data"
  curve: "curve"
  curve_definition: "definition"
  curve_time_series: "timeseries"
  fx_forecast: "fx_forecast"
  fx_quotes: "quotes"
  index_composition: "underlyings"
  search: "search"
  shift_days: "date"
  time_series: "timeseries"
  year_fraction: "year_fraction"
  yield_forecast: "yield_forecast"

